import type { WebsiteConfig } from "./website-config.types";

export const DEFAULT_WEBSITE_CONFIG: WebsiteConfig = {
  settings: {
    siteName: "RIOTOUS",
    tagline: "We Don't Follow Trends. We Print Them.",
    maintenanceMode: false,
    maintenanceMessage:
      "We are currently updating our store with fresh drops. Please check back shortly!",
    currency: "INR",
    storeEmail: "support@riotous.store",
    storePhone: "+91 98980 00000",
    address: "Surat, Gujarat, India",
  },
  seo: {
    metaTitle: "RIOTOUS — We Don't Follow Trends. We Print Them.",
    metaDescription:
      "Premium DTF printed streetwear made in India. Custom apparel for creators, dreamers, and streetwear lovers.",
    ogTitle: "RIOTOUS — Premium DTF Streetwear",
    ogDescription: "Premium DTF printed streetwear made in India. Custom apparel for creators.",
    canonicalUrl: "https://riotous.store",
    keywords: "streetwear, DTF printing, oversized t-shirts, custom apparel, graphic tees, India",
  },
  announcementBar: {
    enabled: true,
    text: "🔥 FREE SHIPPING ON ALL ORDERS OVER ₹1499 · USE CODE 'RIOT10' FOR 10% OFF",
    linkUrl: "/shop",
    linkLabel: "Shop Now",
    backgroundColor: "#DC2626", // brand red
    textColor: "#FFFFFF",
  },
  navigation: {
    items: [
      { id: "nav-1", label: "Shop", to: "/shop", enabled: true },
      { id: "nav-2", label: "Design Your Own", to: "/design", enabled: true },
      { id: "nav-3", label: "About", to: "/about", enabled: true },
      { id: "nav-4", label: "Contact", to: "/contact", enabled: true },
    ],
  },
  hero: {
    enabled: true,
    badge: "Premium DTF apparel · Made in India",
    heading: "We Don't Follow Trends.\nWe Print Them.",
    subheading: "Streetwear Reimagined",
    description:
      "Premium DTF printed apparel made for creators, dreamers and streetwear lovers. Oversized tees and graphic prints, designed and made in India.",
    primaryCtaText: "Shop Now",
    primaryCtaLink: "/shop",
    secondaryCtaText: "Design Your Own",
    secondaryCtaLink: "/design",
    videoUrl: "/videos/riotus-hero.mp4",
    imageUrl: "",
    alignment: "left",
    animation: "default",
    showTShirtBadge: true,
  },
  collections: {
    enabled: true,
    badge: "Collections",
    heading: "Shop the drop.",
    viewAllLink: "/shop",
    items: [
      {
        id: "col-1",
        title: "DTF Printed Tees",
        tag: "Signature",
        to: "/shop",
        backgroundColor: "#DC2626",
        enabled: true,
      },
      {
        id: "col-2",
        title: "Custom Printing",
        tag: "Design your own",
        to: "/design",
        backgroundColor: "#171717",
        enabled: true,
      },
      {
        id: "col-3",
        title: "Oversized",
        tag: "New silhouettes",
        to: "/shop",
        backgroundColor: "#1E293B",
        enabled: true,
      },
      {
        id: "col-4",
        title: "Best Sellers",
        tag: "Community favorites",
        to: "/shop",
        backgroundColor: "#0F172A",
        enabled: true,
      },
    ],
  },
  featuredProducts: {
    enabled: true,
    badge: "Selected Drops",
    heading: "Featured.",
    viewAllLink: "/shop",
    productIds: [],
    limit: 8,
  },
  banners: [
    {
      id: "ban-1",
      title: "Mid-Season Streetwear Drop",
      subtitle: "Limited Edition Releases",
      description: "Get 20% off all heavyweight drop-shoulder oversized tees this week only.",
      ctaText: "Explore Drop",
      ctaLink: "/shop",
      badge: "Limited Stock",
      status: "active",
      enabled: true,
      backgroundColor: "#111827",
      textColor: "#FFFFFF",
    },
  ],
  features: {
    enabled: true,
    badge: "Why RIOTOUS",
    heading: "Built for the ones who create.",
    items: [
      {
        id: "feat-1",
        icon: "Sparkles",
        title: "Premium fabric",
        body: "Heavyweight combed cotton. Cut and sewn for durability and drape.",
        enabled: true,
      },
      {
        id: "feat-2",
        icon: "Package",
        title: "Long-lasting DTF prints",
        body: "Ultra-vibrant direct-to-film prints that survive the wash and the mosh.",
        enabled: true,
      },
      {
        id: "feat-3",
        icon: "Truck",
        title: "Fast shipping",
        body: "Free shipping over ₹1499. Dispatched within 24 hours across India.",
        enabled: true,
      },
      {
        id: "feat-4",
        icon: "RotateCcw",
        title: "Easy returns",
        body: "7-day no-questions returns. If you don't love it, send it back.",
        enabled: true,
      },
      {
        id: "feat-5",
        icon: "MapPin",
        title: "Made in India",
        body: "Designed, printed, and packed by our team. Fair wages, fair work.",
        enabled: true,
      },
      {
        id: "feat-6",
        icon: "ShieldCheck",
        title: "Premium packaging",
        body: "Every drop arrives in signature RIOTOUS packaging. Unboxing is part of the fit.",
        enabled: true,
      },
    ],
  },
  designCta: {
    enabled: true,
    badge: "Design Studio",
    heading: "Your art. Our shirt.\nZero limits.",
    description:
      "Upload artwork, add text, place it front, back or sleeve — see it live before you order.",
    ctaText: "Open the Studio",
    ctaLink: "/design",
  },
  reviewsSection: {
    enabled: true,
    badge: "Reviews",
    heading: "Straight from the community.",
    description: "Verified customer reviews and experiences with RIOTOUS streetwear.",
  },
  footer: {
    enabled: true,
    brandTagline:
      "RIOTOUS creates heavyweight, DTF-printed streetwear made in India. Built for creators, artists, and culture shifters.",
    contactEmail: "support@riotous.store",
    contactPhone: "+91 98980 00000",
    copyrightText: `© ${new Date().getFullYear()} RIOTOUS Inc. All rights reserved.`,
    socialLinks: [
      {
        id: "soc-1",
        platform: "instagram",
        label: "Instagram",
        url: "https://instagram.com/riotous.store",
        enabled: true,
      },
      {
        id: "soc-2",
        platform: "twitter",
        label: "X (Twitter)",
        url: "https://twitter.com/riotous_store",
        enabled: true,
      },
      {
        id: "soc-3",
        platform: "youtube",
        label: "YouTube",
        url: "https://youtube.com/@riotous",
        enabled: true,
      },
      {
        id: "soc-4",
        platform: "whatsapp",
        label: "WhatsApp",
        url: "https://wa.me/919898000000",
        enabled: true,
      },
    ],
    sections: [
      {
        id: "foot-sec-1",
        title: "Shop",
        enabled: true,
        links: [
          { id: "fl-1", label: "All Products", url: "/shop" },
          { id: "fl-2", label: "Design Your Own", url: "/design" },
          { id: "fl-3", label: "Size Guide", url: "/shop" },
        ],
      },
      {
        id: "foot-sec-2",
        title: "Company",
        enabled: true,
        links: [
          { id: "fl-4", label: "About Us", url: "/about" },
          { id: "fl-5", label: "Contact Us", url: "/contact" },
          { id: "fl-6", label: "Return Policy", url: "/refund-policy" },
          { id: "fl-7", label: "Shipping Policy", url: "/shipping-policy" },
          { id: "fl-8", label: "Terms of Service", url: "/terms" },
          { id: "fl-9", label: "Privacy Policy", url: "/privacy" },
        ],
      },
    ],
  },
  sectionOrder: [
    { id: "hero", name: "Hero Section", enabled: true },
    { id: "collections", name: "Collections & Drops", enabled: true },
    { id: "featuredProducts", name: "Featured Products", enabled: true },
    { id: "features", name: "Why Us / Features", enabled: true },
    { id: "banners", name: "Promotional Banners", enabled: true },
    { id: "designCta", name: "Design Studio CTA", enabled: true },
    { id: "reviewsSection", name: "Community Reviews", enabled: true },
  ],
};
