import { createFileRoute } from "@tanstack/react-router";
import type {} from "@tanstack/react-start";

const ROBOTS_TXT_CONTENT = `# ==============================================================================
# RIOTOUS — robots.txt
# Official Store: https://riotous.store
<<<<<<< HEAD
# Optimized for Search Engines & AI Crawlers (Search, Assistant, Training)
# ==============================================================================

# Default policy for all crawlers (including Googlebot, Bingbot, and all AI crawlers:
# OAI-SearchBot, PerplexityBot, ChatGPT-User, Claude-Web, anthropic-ai,
# Perplexity-User, Amazonbot, MistralAI-User, GPTBot, Google-Extended,
# ClaudeBot, CCBot, Applebot-Extended, Bytespider, Meta-ExternalAgent)

=======
# Machine-Readable AI Context: https://riotous.store/llms.txt
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. AI Search & Answer Engines (Real-time indexation & search citations)
# ------------------------------------------------------------------------------
User-agent: OAI-SearchBot
Allow: /
Allow: /shop
Allow: /shop/*
Allow: /product/
Allow: /product/*
Allow: /products/
Allow: /products/*
Allow: /category/
Allow: /category/*
Allow: /collections/
Allow: /collections/*
Allow: /design
Allow: /design/*
Allow: /about
Allow: /contact
Allow: /shipping-policy
Allow: /refund-policy
Allow: /privacy
Allow: /terms
Allow: /assets/
Allow: /products/
Allow: /videos/
Allow: /api/media/
Allow: /api/public/
Allow: /sitemap.xml
Allow: /llms.txt
Disallow: /admin
Disallow: /admin/*
Disallow: /dashboard
Disallow: /dashboard/*
Disallow: /account
Disallow: /account/*
Disallow: /checkout
Disallow: /checkout/*
Disallow: /cart
Disallow: /cart/*
Disallow: /auth
Disallow: /auth/*
Disallow: /auth_
Disallow: /auth_/*
Disallow: /login
Disallow: /login/*
Disallow: /register
Disallow: /register/*
Disallow: /reset-password
Disallow: /reset-password/*
Disallow: /staff
Disallow: /staff/*
Disallow: /settings
Disallow: /settings/*
Disallow: /internal
Disallow: /internal/*
Disallow: /api
Disallow: /api/

User-agent: PerplexityBot
Allow: /
Allow: /shop
Allow: /shop/*
Allow: /product/
Allow: /product/*
Allow: /products/
Allow: /products/*
Allow: /category/
Allow: /category/*
Allow: /collections/
Allow: /collections/*
Allow: /design
Allow: /design/*
Allow: /about
Allow: /contact
Allow: /shipping-policy
Allow: /refund-policy
Allow: /privacy
Allow: /terms
Allow: /assets/
Allow: /products/
Allow: /videos/
Allow: /api/media/
Allow: /api/public/
Allow: /sitemap.xml
Allow: /llms.txt
Disallow: /admin
Disallow: /admin/*
Disallow: /dashboard
Disallow: /dashboard/*
Disallow: /account
Disallow: /account/*
Disallow: /checkout
Disallow: /checkout/*
Disallow: /cart
Disallow: /cart/*
Disallow: /auth
Disallow: /auth/*
Disallow: /auth_
Disallow: /auth_/*
Disallow: /login
Disallow: /login/*
Disallow: /register
Disallow: /register/*
Disallow: /reset-password
Disallow: /reset-password/*
Disallow: /staff
Disallow: /staff/*
Disallow: /settings
Disallow: /settings/*
Disallow: /internal
Disallow: /internal/*
Disallow: /api
Disallow: /api/

User-agent: Claude-Web
Allow: /
Allow: /shop
Allow: /shop/*
Allow: /product/
Allow: /product/*
Allow: /products/
Allow: /products/*
Allow: /category/
Allow: /category/*
Allow: /collections/
Allow: /collections/*
Allow: /design
Allow: /design/*
Allow: /about
Allow: /contact
Allow: /shipping-policy
Allow: /refund-policy
Allow: /privacy
Allow: /terms
Allow: /assets/
Allow: /products/
Allow: /videos/
Allow: /api/media/
Allow: /api/public/
Allow: /sitemap.xml
Allow: /llms.txt
Disallow: /admin
Disallow: /admin/*
Disallow: /dashboard
Disallow: /dashboard/*
Disallow: /account
Disallow: /account/*
Disallow: /checkout
Disallow: /checkout/*
Disallow: /cart
Disallow: /cart/*
Disallow: /auth
Disallow: /auth/*
Disallow: /auth_
Disallow: /auth_/*
Disallow: /login
Disallow: /login/*
Disallow: /register
Disallow: /register/*
Disallow: /reset-password
Disallow: /reset-password/*
Disallow: /staff
Disallow: /staff/*
Disallow: /settings
Disallow: /settings/*
Disallow: /internal
Disallow: /internal/*
Disallow: /api
Disallow: /api/

User-agent: Amazonbot
Allow: /
Allow: /shop
Allow: /shop/*
Allow: /product/
Allow: /product/*
Allow: /products/
Allow: /products/*
Allow: /category/
Allow: /category/*
Allow: /collections/
Allow: /collections/*
Allow: /design
Allow: /design/*
Allow: /about
Allow: /contact
Allow: /shipping-policy
Allow: /refund-policy
Allow: /privacy
Allow: /terms
Allow: /assets/
Allow: /products/
Allow: /videos/
Allow: /api/media/
Allow: /api/public/
Allow: /sitemap.xml
Allow: /llms.txt
Disallow: /admin
Disallow: /admin/*
Disallow: /dashboard
Disallow: /dashboard/*
Disallow: /account
Disallow: /account/*
Disallow: /checkout
Disallow: /checkout/*
Disallow: /cart
Disallow: /cart/*
Disallow: /auth
Disallow: /auth/*
Disallow: /auth_
Disallow: /auth_/*
Disallow: /login
Disallow: /login/*
Disallow: /register
Disallow: /register/*
Disallow: /reset-password
Disallow: /reset-password/*
Disallow: /staff
Disallow: /staff/*
Disallow: /settings
Disallow: /settings/*
Disallow: /internal
Disallow: /internal/*
Disallow: /api
Disallow: /api/

# ------------------------------------------------------------------------------
# 2. AI Assistant & User-Initiated Live Retrieval Crawlers
# ------------------------------------------------------------------------------
User-agent: ChatGPT-User
Allow: /
Allow: /shop
Allow: /shop/*
Allow: /product/
Allow: /product/*
Allow: /products/
Allow: /products/*
Allow: /category/
Allow: /category/*
Allow: /collections/
Allow: /collections/*
Allow: /design
Allow: /design/*
Allow: /about
Allow: /contact
Allow: /shipping-policy
Allow: /refund-policy
Allow: /privacy
Allow: /terms
Allow: /assets/
Allow: /products/
Allow: /videos/
Allow: /api/media/
Allow: /api/public/
Allow: /sitemap.xml
Allow: /llms.txt
Disallow: /admin
Disallow: /admin/*
Disallow: /dashboard
Disallow: /dashboard/*
Disallow: /account
Disallow: /account/*
Disallow: /checkout
Disallow: /checkout/*
Disallow: /cart
Disallow: /cart/*
Disallow: /auth
Disallow: /auth/*
Disallow: /auth_
Disallow: /auth_/*
Disallow: /login
Disallow: /login/*
Disallow: /register
Disallow: /register/*
Disallow: /reset-password
Disallow: /reset-password/*
Disallow: /staff
Disallow: /staff/*
Disallow: /settings
Disallow: /settings/*
Disallow: /internal
Disallow: /internal/*
Disallow: /api
Disallow: /api/

User-agent: Perplexity-User
Allow: /
Allow: /shop
Allow: /shop/*
Allow: /product/
Allow: /product/*
Allow: /products/
Allow: /products/*
Allow: /category/
Allow: /category/*
Allow: /collections/
Allow: /collections/*
Allow: /design
Allow: /design/*
Allow: /about
Allow: /contact
Allow: /shipping-policy
Allow: /refund-policy
Allow: /privacy
Allow: /terms
Allow: /assets/
Allow: /products/
Allow: /videos/
Allow: /api/media/
Allow: /api/public/
Allow: /sitemap.xml
Allow: /llms.txt
Disallow: /admin
Disallow: /admin/*
Disallow: /dashboard
Disallow: /dashboard/*
Disallow: /account
Disallow: /account/*
Disallow: /checkout
Disallow: /checkout/*
Disallow: /cart
Disallow: /cart/*
Disallow: /auth
Disallow: /auth/*
Disallow: /auth_
Disallow: /auth_/*
Disallow: /login
Disallow: /login/*
Disallow: /register
Disallow: /register/*
Disallow: /reset-password
Disallow: /reset-password/*
Disallow: /staff
Disallow: /staff/*
Disallow: /settings
Disallow: /settings/*
Disallow: /internal
Disallow: /internal/*
Disallow: /api
Disallow: /api/

User-agent: anthropic-ai
Allow: /
Allow: /shop
Allow: /shop/*
Allow: /product/
Allow: /product/*
Allow: /products/
Allow: /products/*
Allow: /category/
Allow: /category/*
Allow: /collections/
Allow: /collections/*
Allow: /design
Allow: /design/*
Allow: /about
Allow: /contact
Allow: /shipping-policy
Allow: /refund-policy
Allow: /privacy
Allow: /terms
Allow: /assets/
Allow: /products/
Allow: /videos/
Allow: /api/media/
Allow: /api/public/
Allow: /sitemap.xml
Allow: /llms.txt
Disallow: /admin
Disallow: /admin/*
Disallow: /dashboard
Disallow: /dashboard/*
Disallow: /account
Disallow: /account/*
Disallow: /checkout
Disallow: /checkout/*
Disallow: /cart
Disallow: /cart/*
Disallow: /auth
Disallow: /auth/*
Disallow: /auth_
Disallow: /auth_/*
Disallow: /login
Disallow: /login/*
Disallow: /register
Disallow: /register/*
Disallow: /reset-password
Disallow: /reset-password/*
Disallow: /staff
Disallow: /staff/*
Disallow: /settings
Disallow: /settings/*
Disallow: /internal
Disallow: /internal/*
Disallow: /api
Disallow: /api/

User-agent: MistralAI-User
Allow: /
Allow: /shop
Allow: /shop/*
Allow: /product/
Allow: /product/*
Allow: /products/
Allow: /products/*
Allow: /category/
Allow: /category/*
Allow: /collections/
Allow: /collections/*
Allow: /design
Allow: /design/*
Allow: /about
Allow: /contact
Allow: /shipping-policy
Allow: /refund-policy
Allow: /privacy
Allow: /terms
Allow: /assets/
Allow: /products/
Allow: /videos/
Allow: /api/media/
Allow: /api/public/
Allow: /sitemap.xml
Allow: /llms.txt
Disallow: /admin
Disallow: /admin/*
Disallow: /dashboard
Disallow: /dashboard/*
Disallow: /account
Disallow: /account/*
Disallow: /checkout
Disallow: /checkout/*
Disallow: /cart
Disallow: /cart/*
Disallow: /auth
Disallow: /auth/*
Disallow: /auth_
Disallow: /auth_/*
Disallow: /login
Disallow: /login/*
Disallow: /register
Disallow: /register/*
Disallow: /reset-password
Disallow: /reset-password/*
Disallow: /staff
Disallow: /staff/*
Disallow: /settings
Disallow: /settings/*
Disallow: /internal
Disallow: /internal/*
Disallow: /api
Disallow: /api/

# ------------------------------------------------------------------------------
# 3. AI Model-Training Crawlers (Disallowed per content protection policy)
# ------------------------------------------------------------------------------
User-agent: GPTBot
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: ClaudeBot
Disallow: /

User-agent: CCBot
Disallow: /

User-agent: Applebot-Extended
Disallow: /

User-agent: Bytespider
Disallow: /

User-agent: Meta-ExternalAgent
Disallow: /

# ------------------------------------------------------------------------------
# 4. Standard Search Engines (Googlebot, Bingbot, etc.) & Default Fallback
# ------------------------------------------------------------------------------
>>>>>>> cc6dd8716725a6df175d1abd63e87ad00696de5e
User-agent: *
Allow: /
Allow: /shop
Allow: /shop/*
Allow: /product/
Allow: /product/*
Allow: /products/
Allow: /products/*
Allow: /category/
Allow: /category/*
Allow: /collections/
Allow: /collections/*
Allow: /design
Allow: /design/*
Allow: /about
Allow: /contact
Allow: /shipping-policy
Allow: /refund-policy
Allow: /privacy
Allow: /terms
Allow: /assets/
Allow: /products/
Allow: /videos/
Allow: /api/media/
Allow: /api/public/
Allow: /sitemap.xml
Allow: /llms.txt
Disallow: /admin
Disallow: /admin/*
Disallow: /dashboard
Disallow: /dashboard/*
Disallow: /account
Disallow: /account/*
Disallow: /checkout
Disallow: /checkout/*
Disallow: /cart
Disallow: /cart/*
Disallow: /auth
Disallow: /auth/*
Disallow: /auth_
Disallow: /auth_/*
Disallow: /login
Disallow: /login/*
Disallow: /register
Disallow: /register/*
Disallow: /reset-password
Disallow: /reset-password/*
Disallow: /staff
Disallow: /staff/*
Disallow: /settings
Disallow: /settings/*
Disallow: /internal
Disallow: /internal/*
Disallow: /api
Disallow: /api/

# ------------------------------------------------------------------------------
# Sitemap & AI Context Discovery
# ------------------------------------------------------------------------------
Sitemap: https://riotous.store/sitemap.xml
`;

export const Route = createFileRoute("/robots.txt")({
  server: {
    handlers: {
      GET: async () => {
        return new Response(ROBOTS_TXT_CONTENT, {
          headers: {
            "Content-Type": "text/plain; charset=utf-8",
            "Cache-Control": "public, max-age=3600",
          },
        });
      },
    },
  },
});
