-- Cloudflare D1 Full Relational Data Migration
-- Database: riotous-db
-- Version: 0003_populate_full_relational_data.sql

-- 1. Categories
INSERT INTO categories (id, name, slug, description) VALUES ('cat_oversized', 'Oversized Tees', 'oversized-tees', 'Heavyweight 240+ GSM oversized streetwear silhouette.') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, description) VALUES ('cat_essential', 'Essential Tees', 'essential-tees', 'Daily wear premium breathable combed cotton tees.') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, description) VALUES ('cat_classic', 'Classic Tees', 'classic-tees', 'Timeless cut, colorfast reactive dye streetwear basics.') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, description) VALUES ('cat_heavyweight', 'Heavyweight Tees', 'heavyweight-tees', '260 GSM dense french terry structural boxy fit tees.') ON CONFLICT (id) DO NOTHING;

-- 2. Profiles (Customers)
INSERT INTO profiles (id, email, password_hash, full_name, role, status, permissions) VALUES ('usr_cust_1', 'aarav.sharma@example.com', '28e75cfdc4bbd91da3c6046e9fc0a316b2cf771f286b2bb6ee8119eb1ea1e459', 'Aarav Sharma', 'customer', 'Active', '{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO profiles (id, email, password_hash, full_name, role, status, permissions) VALUES ('usr_cust_2', 'priya.patel@example.com', '28e75cfdc4bbd91da3c6046e9fc0a316b2cf771f286b2bb6ee8119eb1ea1e459', 'Priya Patel', 'customer', 'Active', '{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO profiles (id, email, password_hash, full_name, role, status, permissions) VALUES ('usr_cust_3', 'rohan.v@example.com', '28e75cfdc4bbd91da3c6046e9fc0a316b2cf771f286b2bb6ee8119eb1ea1e459', 'Rohan Verma', 'customer', 'Active', '{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO profiles (id, email, password_hash, full_name, role, status, permissions) VALUES ('usr_cust_4', 'ananya.iyer@example.com', '28e75cfdc4bbd91da3c6046e9fc0a316b2cf771f286b2bb6ee8119eb1ea1e459', 'Ananya Iyer', 'customer', 'Active', '{}') ON CONFLICT (id) DO NOTHING;

-- 3. Product Highlights, Specifications, and Offers
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-1', 'prod-oversized-black-tee', '/products/zoro-black-1.jpg', '240 GSM Combed Cotton', 'Heavyweight premium cotton built for structure and all-day comfort.', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-2', 'prod-oversized-black-tee', '/products/zoro-black-2.jpg', 'Drop Shoulder Boxy Fit', 'Signature streetwear drape with relaxed armholes and boxy cut.', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-1', 'prod-oversized-black-tee', 'Fit', 'Oversized Fit', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-2', 'prod-oversized-black-tee', 'Fabric', '100% Super Combed Cotton', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-3', 'prod-oversized-black-tee', 'GSM', '240 GSM', 3, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-4', 'prod-oversized-black-tee', 'Neck', 'Ribbed Crew Neck', 4, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-5', 'prod-oversized-black-tee', 'Sleeve', 'Half Drop Sleeve', 5, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-6', 'prod-oversized-black-tee', 'Pattern', 'Graphic Screenprint', 6, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-7', 'prod-oversized-black-tee', 'Country of Origin', 'India', 7, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_offers (id, product_id, title, description, discount_type, discount_value, promo_code, minimum_quantity, maximum_quantity, eligible_products, eligible_categories, start_date, end_date, is_active, display_order, terms_and_conditions) VALUES ('off-riotous20-fallback', 'prod-oversized-black-tee', 'BUY 3 GET 20% OFF', 'Get 20% off when you buy 3 or more streetwear pieces.', 'percentage', 20, 'RIOTOUS20', 3, NULL, '[]', '[]', NULL, NULL, 1, 1, 'Use promo code RIOTOUS20 at checkout. Applicable on cart subtotals with 3 or more streetwear products. Cannot be combined with other coupons.') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_offers (id, product_id, title, description, discount_type, discount_value, promo_code, minimum_quantity, maximum_quantity, eligible_products, eligible_categories, start_date, end_date, is_active, display_order, terms_and_conditions) VALUES ('off-b2g1-fallback', 'prod-oversized-black-tee', 'BUY 2 GET 1 FREE', 'Add any 3 items to your bag and get 1 free automatically at checkout.', 'buy_x_get_y', 1, NULL, 3, NULL, '[]', '[]', NULL, NULL, 1, 2, 'Buy 2 items and get 1 free automatically at checkout. Lowest priced eligible item will be free. Applicable on all oversized and streetwear tees.') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_offers (id, product_id, title, description, discount_type, discount_value, promo_code, minimum_quantity, maximum_quantity, eligible_products, eligible_categories, start_date, end_date, is_active, display_order, terms_and_conditions) VALUES ('off-save200-fallback', 'prod-oversized-black-tee', 'FLAT ₹200 OFF', 'Flat ₹200 discount on your order.', 'fixed_amount', 200, 'SAVE200', 1, NULL, '[]', '[]', NULL, NULL, 1, 3, 'Use coupon code SAVE200 at checkout. Flat ₹200 discount applicable on orders.') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-pwt-1', 'prod-premium-white-tee', '/products/zoro-olive-1.jpg', '180 GSM Ring-Spun Cotton', 'Lightweight and ultra-breathable weave ideal for hot days and layering.', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-pwt-2', 'prod-premium-white-tee', '/products/zoro-olive-2.jpg', 'Tailored Modern Regular Fit', 'Clean silhouette cut close through the chest and shoulders without clinging.', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-pwt-1', 'prod-premium-white-tee', 'Fit', 'Regular Fit', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-pwt-2', 'prod-premium-white-tee', 'Fabric', '100% Ring-Spun Cotton', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-pwt-3', 'prod-premium-white-tee', 'GSM', '180 GSM', 3, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-pwt-4', 'prod-premium-white-tee', 'Neck', 'Round Neck', 4, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-pwt-5', 'prod-premium-white-tee', 'Sleeve', 'Regular Half Sleeve', 5, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-pwt-6', 'prod-premium-white-tee', 'Finish', 'Bio-Washed & Silicon Softened', 6, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-pwt-7', 'prod-premium-white-tee', 'Country of Origin', 'India', 7, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_offers (id, product_id, title, description, discount_type, discount_value, promo_code, minimum_quantity, maximum_quantity, eligible_products, eligible_categories, start_date, end_date, is_active, display_order, terms_and_conditions) VALUES ('off-pwt-riotous10', 'prod-premium-white-tee', '10% OFF ON ALL ORDERS', 'Get 10% instant discount on your order with coupon code RIOTOUS10.', 'coupon', 10, 'RIOTOUS10', 1, NULL, '[]', '[]', NULL, NULL, 1, 1, 'Use coupon code RIOTOUS10 during checkout. Applies to entire order. Valid for single usage per user.') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_offers (id, product_id, title, description, discount_type, discount_value, promo_code, minimum_quantity, maximum_quantity, eligible_products, eligible_categories, start_date, end_date, is_active, display_order, terms_and_conditions) VALUES ('off-pwt-flat100', 'prod-premium-white-tee', 'FLAT ₹100 OFF ON 2+ TEES', 'Save ₹100 extra when purchasing any 2 or more essential tees.', 'fixed_amount', 100, 'DOUBLE100', 2, NULL, '[]', '[]', NULL, NULL, 1, 2, 'Add at least 2 tees to your cart and apply coupon DOUBLE100 to get ₹100 off your order total.') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-crts-1', 'prod-classic-red-tee', '/products/zenitsu-maroon-1.jpg', 'Rich Crimson Reactive Dye', 'Resistant to wash fading, staying saturated through repeat cycles.', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-crts-2', 'prod-classic-red-tee', '/products/zenitsu-maroon-2.jpg', 'Everyday Breathable Fit', 'Versatile fit designed for comfort whether relaxing or on the move.', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-crts-1', 'prod-classic-red-tee', 'Fit', 'Classic Fit', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-crts-2', 'prod-classic-red-tee', 'Fabric', '100% Combed Cotton', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-crts-3', 'prod-classic-red-tee', 'GSM', '190 GSM', 3, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-crts-4', 'prod-classic-red-tee', 'Neck', 'Crew Neck', 4, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-crts-5', 'prod-classic-red-tee', 'Sleeve', 'Short Sleeve', 5, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-crts-6', 'prod-classic-red-tee', 'Pattern', 'Solid', 6, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-crts-7', 'prod-classic-red-tee', 'Country of Origin', 'India', 7, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_offers (id, product_id, title, description, discount_type, discount_value, promo_code, minimum_quantity, maximum_quantity, eligible_products, eligible_categories, start_date, end_date, is_active, display_order, terms_and_conditions) VALUES ('off-crts-combo', 'prod-classic-red-tee', 'BUY 2 FOR ₹1,499', 'Special bundle pricing when buying 2 classic tees together.', 'flat_price', 1499, NULL, 2, NULL, '[]', '[]', NULL, NULL, 1, 1, 'Bundle price of ₹1,499 applies automatically when 2 classic tees are added to bag. No coupon required.') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-hwg-1', 'prod-heavyweight-grey-tee', '/products/zoro-black-2.jpg', '260 GSM Ultra-Heavyweight', 'Our thickest jersey fabric holds a crisp architectural silhouette without collapsing.', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-hwg-2', 'prod-heavyweight-grey-tee', '/products/zoro-black-1.jpg', '1.25" Chunky Ribbed Neck', 'Heavy-gauge collar ribbing that stays flat and tight wear after wear.', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-hwg-1', 'prod-heavyweight-grey-tee', 'Fit', 'Boxy Oversized Fit', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-hwg-2', 'prod-heavyweight-grey-tee', 'Fabric', '90% Cotton, 10% Heather Polyester', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-hwg-3', 'prod-heavyweight-grey-tee', 'GSM', '260 GSM', 3, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-hwg-4', 'prod-heavyweight-grey-tee', 'Neck', '1.25" Chunky Ribbed Neck', 4, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-hwg-5', 'prod-heavyweight-grey-tee', 'Sleeve', 'Extended Drop Half Sleeve', 5, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-hwg-6', 'prod-heavyweight-grey-tee', 'Pattern', 'Heather Melange', 6, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-hwg-7', 'prod-heavyweight-grey-tee', 'Country of Origin', 'India', 7, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_offers (id, product_id, title, description, discount_type, discount_value, promo_code, minimum_quantity, maximum_quantity, eligible_products, eligible_categories, start_date, end_date, is_active, display_order, terms_and_conditions) VALUES ('off-hwg-b2g1', 'prod-heavyweight-grey-tee', 'BUY 2 GET 1 FREE', 'Add any 3 heavyweight products to your bag and get 1 free automatically.', 'buy_x_get_y', 1, NULL, 3, NULL, '[]', '[]', NULL, NULL, 1, 1, 'Buy 2 items and get 1 free at checkout. Applicable on all heavyweight tees. Lowest value item is discounted.') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_offers (id, product_id, title, description, discount_type, discount_value, promo_code, minimum_quantity, maximum_quantity, eligible_products, eligible_categories, start_date, end_date, is_active, display_order, terms_and_conditions) VALUES ('off-hwg-save200', 'prod-heavyweight-grey-tee', 'EXTRA ₹200 OFF ON ₹2,000+', 'Save ₹200 instantly on high-value cart totals with code HEAVY200.', 'fixed_amount', 200, 'HEAVY200', 2, NULL, '[]', '[]', NULL, NULL, 1, 2, 'Applies to orders of ₹2,000 or more containing at least 2 items. Use code HEAVY200 at checkout.') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-stb-1', 'prod-streetwear-blue-tee', '/products/zenitsu-maroon-2.jpg', 'Vintage Pigment Garment Wash', 'Specialized enzyme fade gives every piece a unique high-street patina.', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-stb-2', 'prod-streetwear-blue-tee', '/products/zenitsu-maroon-1.jpg', 'Relaxed Streetwear Silhouette', 'Drop shoulder with slightly lengthened body for that effortless oversized look.', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-stb-1', 'prod-streetwear-blue-tee', 'Fit', 'Relaxed Streetwear Fit', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-stb-2', 'prod-streetwear-blue-tee', 'Fabric', '100% Combed Cotton', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-stb-3', 'prod-streetwear-blue-tee', 'GSM', '220 GSM', 3, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-stb-4', 'prod-streetwear-blue-tee', 'Neck', 'Ribbed Crew Neck', 4, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-stb-5', 'prod-streetwear-blue-tee', 'Sleeve', 'Drop Shoulder Half Sleeve', 5, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-stb-6', 'prod-streetwear-blue-tee', 'Finish', 'Vintage Acid Wash', 6, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-stb-7', 'prod-streetwear-blue-tee', 'Country of Origin', 'India', 7, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_offers (id, product_id, title, description, discount_type, discount_value, promo_code, minimum_quantity, maximum_quantity, eligible_products, eligible_categories, start_date, end_date, is_active, display_order, terms_and_conditions) VALUES ('off-stb-b2g1', 'prod-streetwear-blue-tee', 'BUY 2 GET 1 FREE', 'Mix & match any 3 streetwear tees and get 1 free automatically.', 'buy_x_get_y', 1, NULL, 3, NULL, '[]', '[]', NULL, NULL, 1, 1, 'Buy 2 streetwear tees and get 1 free automatically at checkout. Lowest value tee is free.') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_offers (id, product_id, title, description, discount_type, discount_value, promo_code, minimum_quantity, maximum_quantity, eligible_products, eligible_categories, start_date, end_date, is_active, display_order, terms_and_conditions) VALUES ('off-stb-street15', 'prod-streetwear-blue-tee', '15% OFF STREETWEAR', 'Get 15% off with coupon code STREET15.', 'percentage', 15, 'STREET15', 1, NULL, '[]', '[]', NULL, NULL, 1, 2, 'Apply promo code STREET15 at checkout to receive 15% discount on this item.') ON CONFLICT (id) DO NOTHING;
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-baki-1', 'prod-baki-hanma-oversized-tee', '/products/zoro-black-1.jpg', '240 GSM Dense Cotton', 'Heavyweight premium cotton built for structure and all-day comfort.', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_highlights (id, product_id, image_url, title, description, display_order, is_active) VALUES ('hl-baki-2', 'prod-baki-hanma-oversized-tee', '/products/zoro-black-2.jpg', 'Drop Shoulder Boxy Fit', 'Signature streetwear drape with relaxed armholes and boxy cut.', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-baki-1', 'prod-baki-hanma-oversized-tee', 'Fit', 'Oversized Fit', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-baki-2', 'prod-baki-hanma-oversized-tee', 'Fabric', '100% Super Combed Cotton', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-baki-3', 'prod-baki-hanma-oversized-tee', 'GSM', '240 GSM', 3, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-baki-4', 'prod-baki-hanma-oversized-tee', 'Neck', 'Ribbed Crew Neck', 4, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-baki-5', 'prod-baki-hanma-oversized-tee', 'Sleeve', 'Half Drop Sleeve', 5, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_specifications (id, product_id, label, value, display_order, is_active) VALUES ('sp-baki-6', 'prod-baki-hanma-oversized-tee', 'Country of Origin', 'India', 6, 1) ON CONFLICT (id) DO NOTHING;

-- 4. Orders
INSERT INTO orders (id, user_id, order_number, subtotal, discount_amount, discount_code, shipping_charge, tax_amount, total_amount, currency, status, payment_status, payment_method, stock_state, shipping_name, shipping_email, shipping_phone, shipping_address, billing_address, courier_name, tracking_number, tracking_url, shipped_at, created_at) VALUES ('ord_1001', 'usr_cust_1', 'ORD-9842', 1499, 150, 'RIOTOUS10', 0, 0, 1349, 'INR', 'Shipped', 'Paid', 'Razorpay (Online)', 'Normal', 'Aarav Sharma', 'aarav.sharma@example.com', '+91 98765 43210', 'Flat 402, Skyline Residency, Bandra West, Mumbai, Maharashtra 400050', 'Flat 402, Skyline Residency, Bandra West, Mumbai, Maharashtra 400050', 'BlueDart Express', 'BD982341209IN', 'https://www.bluedart.com/tracking/BD982341209IN', '2026-09-30T10:00:00.000Z', '2026-09-29T14:30:00.000Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, user_id, order_number, subtotal, discount_amount, discount_code, shipping_charge, tax_amount, total_amount, currency, status, payment_status, payment_method, stock_state, shipping_name, shipping_email, shipping_phone, shipping_address, billing_address, courier_name, tracking_number, tracking_url, shipped_at, created_at) VALUES ('ord_1002', 'usr_cust_2', 'ORD-9843', 1299, 0, NULL, 50, 0, 1349, 'INR', 'Processing', 'Paid', 'UPI (PhonePe)', 'Normal', 'Priya Patel', 'priya.patel@example.com', '+91 98123 45678', '12, Shanti Niketan Society, Navrangpura, Ahmedabad, Gujarat 380009', '12, Shanti Niketan Society, Navrangpura, Ahmedabad, Gujarat 380009', 'Delhivery', 'DLV10928374', 'https://www.delhivery.com/track/package/DLV10928374', NULL, '2026-10-01T09:15:00.000Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, user_id, order_number, subtotal, discount_amount, discount_code, shipping_charge, tax_amount, total_amount, currency, status, payment_status, payment_method, stock_state, shipping_name, shipping_email, shipping_phone, shipping_address, billing_address, courier_name, tracking_number, tracking_url, shipped_at, created_at) VALUES ('ord_1003', 'usr_cust_3', 'ORD-9844', 1799, 0, NULL, 0, 0, 1799, 'INR', 'Confirmed', 'Pending', 'Cash on Delivery', 'Normal', 'Rohan Verma', 'rohan.v@example.com', '+91 97234 56789', 'Tower B-601, Cyber City Greens, Sector 24, Gurugram, Haryana 122002', 'Tower B-601, Cyber City Greens, Sector 24, Gurugram, Haryana 122002', NULL, NULL, NULL, NULL, '2026-10-02T11:00:00.000Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, user_id, order_number, subtotal, discount_amount, discount_code, shipping_charge, tax_amount, total_amount, currency, status, payment_status, payment_method, stock_state, shipping_name, shipping_email, shipping_phone, shipping_address, billing_address, courier_name, tracking_number, tracking_url, shipped_at, created_at) VALUES ('ord_1004', 'usr_cust_4', 'ORD-9845', 1399, 0, NULL, 0, 0, 1399, 'INR', 'Pending', 'Pending', 'Cash on Delivery', 'Normal', 'Ananya Iyer', 'ananya.iyer@example.com', '+91 99345 67890', '45, Indiranagar 100ft Road, Bangalore, Karnataka 560038', '45, Indiranagar 100ft Road, Bangalore, Karnataka 560038', NULL, NULL, NULL, NULL, '2026-10-02T18:00:00.000Z') ON CONFLICT (id) DO NOTHING;

-- 5. Order Items
INSERT INTO order_items (id, order_id, product_id, variant_id, product_name, product_image, quantity, price, unit_price, total_price, selected_size, selected_color, size, color, sku, subtotal, created_at) VALUES ('item_1001', 'ord_1001', 'prod-oversized-black-tee', 'var-obts-blk-l', 'Oversized Black T-Shirt', '/products/zoro-black-1.jpg', 1, 1199, 1199, 1199, 'L', 'Black', 'L', 'Black', 'OBTS-BLK-L', 1199, '2026-09-29T14:30:00.000Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO order_items (id, order_id, product_id, variant_id, product_name, product_image, quantity, price, unit_price, total_price, selected_size, selected_color, size, color, sku, subtotal, created_at) VALUES ('item_1002', 'ord_1002', 'prod-premium-white-tee', 'var-pwt-wht-m', 'Premium White T-Shirt', '/products/zoro-olive-1.jpg', 1, 899, 899, 899, 'M', 'White', 'M', 'White', 'PWT-WHT-M', 899, '2026-10-01T09:15:00.000Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO order_items (id, order_id, product_id, variant_id, product_name, product_image, quantity, price, unit_price, total_price, selected_size, selected_color, size, color, sku, subtotal, created_at) VALUES ('item_1003', 'ord_1003', 'prod-heavyweight-grey-tee', 'var-hwg-gry-xl', 'Heavyweight Grey T-Shirt', '/products/zoro-black-2.jpg', 1, 1149, 1149, 1149, 'XL', 'Grey', 'XL', 'Grey', 'HWG-GRY-XL', 1149, '2026-10-02T11:00:00.000Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO order_items (id, order_id, product_id, variant_id, product_name, product_image, quantity, price, unit_price, total_price, selected_size, selected_color, size, color, sku, subtotal, created_at) VALUES ('item_1004', 'ord_1004', 'prod-classic-red-tee', 'var-crts-red-s', 'Classic Red T-Shirt', '/products/zenitsu-maroon-1.jpg', 1, 849, 849, 849, 'S', 'Red', 'S', 'Red', 'CRTS-RED-S', 849, '2026-10-02T18:00:00.000Z') ON CONFLICT (id) DO NOTHING;

-- 6. Coupon Usage
INSERT INTO coupon_usage (id, coupon_id, order_id, customer_id, customer_email, coupon_code, discount_amount, order_amount, used_at) VALUES ('cusg_demo_1', 'cpn_riotous10', 'ord_1001', 'usr_cust_1', 'aarav.sharma@example.com', 'RIOTOUS10', 150, 1500, '2026-09-30T10:00:00.000Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO coupon_usage (id, coupon_id, order_id, customer_id, customer_email, coupon_code, discount_amount, order_amount, used_at) VALUES ('cusg_demo_2', 'cpn_welcome200', 'ord_1002', 'usr_cust_2', 'priya.patel@example.com', 'WELCOME200', 200, 1800, '2026-10-01T09:15:00.000Z') ON CONFLICT (id) DO NOTHING;